IMPORT LIBRARIES

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

IMPORT DATASET

In [2]:
data = pd.read_csv('Data.csv')
print(data)

     Sample code number  Clump Thickness  Uniformity of Cell Size  \
0               1000025                5                        1   
1               1002945                5                        4   
2               1015425                3                        1   
3               1016277                6                        8   
4               1017023                4                        1   
..                  ...              ...                      ...   
678              776715                3                        1   
679              841769                2                        1   
680              888820                5                       10   
681              897471                4                        8   
682              897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                           1                  1                            2   
1        

In [3]:
x = data.iloc[:, :-1].values
print(x)

[[1000025       5       1 ...       3       1       1]
 [1002945       5       4 ...       3       2       1]
 [1015425       3       1 ...       3       1       1]
 ...
 [ 888820       5      10 ...       8      10       2]
 [ 897471       4       8 ...      10       6       1]
 [ 897471       4       8 ...      10       4       1]]


In [4]:
y = data.iloc[:, -1].values
print(y)

[2 2 2 2 2 4 2 2 2 2 2 2 4 2 4 4 2 2 4 2 4 4 2 2 4 2 2 2 2 2 2 4 2 2 2 4 2
 4 4 4 4 4 4 2 4 2 2 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4 2 4 2 4 4 2 2 4 2 4 4 2
 2 2 2 2 2 2 2 2 4 4 4 4 2 2 2 2 2 2 2 2 2 2 4 4 4 4 2 4 4 4 4 4 2 4 2 4 4
 4 2 2 2 4 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 4 2 2 4 2 4
 4 2 2 4 2 2 4 4 2 2 2 2 4 4 2 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 4 2 4 4 4 2 4
 4 2 2 2 2 2 2 2 2 4 4 2 2 2 4 4 2 2 2 4 4 2 4 4 4 2 2 4 2 2 4 4 4 4 2 4 4
 2 4 4 4 2 4 2 4 4 4 4 2 2 2 2 2 2 4 4 2 2 4 2 4 4 4 2 2 2 2 4 4 4 4 4 2 4
 4 4 2 4 2 4 4 2 2 2 2 4 2 2 4 4 4 4 4 2 4 4 2 2 4 4 2 2 4 4 2 4 2 4 4 2 2
 4 2 2 2 4 2 2 4 4 2 2 4 2 4 2 2 4 2 4 4 4 2 2 4 4 2 4 2 2 4 4 2 2 2 4 2 2
 2 4 4 2 2 2 4 2 2 4 4 4 4 4 4 2 2 2 2 4 4 2 2 2 2 2 2 2 2 2 2 2 2 2 4 2 2
 2 2 4 2 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 2 2 2 2 2 2 2 2 4 2 4 2 4 2 2 2 2 4
 2 2 2 4 2 4 2 2 2 2 2 2 2 4 4 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 2 4 2 4 4 4 2
 2 2 2 2 2 2 4 4 4 2 2 2 2 2 2 2 2 2 2 2 4 2 2 4 4 2 2 2 4 4 4 2 4 2 4 2 2
 2 2 2 2 2 2 2 2 2 2 4 2 

SPLITING THE DATA INTO TRAINNG AND TEST SETS (TEST SIZE = 20%)

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 20)

In [6]:
print(x_train)

[[ 730881       7       6 ...       7       4       6]
 [1238915       5       1 ...       3       1       1]
 [1114570       5       3 ...       3       1       1]
 ...
 [ 486283       3       1 ...       3       1       1]
 [1084139       6       3 ...       4       1       1]
 [ 428598       1       1 ...       2       1       1]]


In [7]:
print(x_test)

[[1044572       8       7 ...       5       5       4]
 [1174009       5       1 ...       2       1       1]
 [ 690557       5       1 ...       2       1       1]
 ...
 [1313325       4      10 ...       9      10       1]
 [1183240       4       1 ...       2       1       1]
 [1016277       6       8 ...       3       7       1]]


In [8]:
print(y_train)

[4 2 2 4 4 4 4 2 2 4 4 4 4 2 4 4 2 4 2 2 4 2 4 2 2 4 2 4 2 2 2 4 4 2 2 2 4
 2 4 2 2 4 2 2 2 4 2 4 2 2 2 4 2 4 4 4 2 2 2 2 4 2 4 2 2 2 2 2 4 2 2 2 2 2
 2 4 2 2 2 2 2 2 2 2 2 2 2 4 2 2 2 2 2 2 2 2 2 2 4 2 2 4 4 2 2 4 4 2 2 2 4
 2 2 4 2 4 2 2 2 2 2 2 4 4 2 2 2 2 2 2 2 2 4 2 2 4 4 2 2 4 2 2 2 2 4 4 2 2
 2 2 2 4 4 2 2 4 4 2 4 2 2 2 2 4 4 2 4 4 4 2 4 2 2 2 4 2 2 2 2 4 2 2 2 2 4
 2 4 2 2 2 2 4 2 2 2 2 2 4 4 2 4 2 2 2 4 2 4 4 2 2 4 2 4 2 2 2 2 2 4 2 4 4
 4 2 2 2 2 2 4 4 2 2 2 2 4 2 4 2 4 2 2 2 2 2 4 2 2 2 2 2 4 4 4 2 4 2 4 2 4
 4 4 4 4 2 4 2 4 2 4 2 4 2 2 4 4 4 2 4 2 2 4 2 2 2 4 2 4 4 4 2 2 4 2 2 2 2
 2 2 4 2 4 4 2 4 2 4 2 4 2 2 2 4 2 4 4 2 2 4 2 2 2 4 2 2 2 2 2 2 2 4 2 4 2
 2 2 4 4 2 2 2 2 2 2 4 4 4 4 2 2 2 4 2 2 2 4 4 4 4 2 4 4 4 4 2 4 2 2 2 2 4
 4 2 2 2 2 4 4 2 4 2 4 2 4 4 2 2 2 2 2 4 2 2 2 2 2 2 4 2 2 2 4 4 4 4 4 2 2
 4 2 2 2 4 4 2 2 2 2 2 2 2 2 4 4 4 4 4 4 2 2 2 4 2 4 2 2 4 4 2 4 2 2 2 2 4
 4 2 4 2 2 2 2 2 4 2 2 2 4 4 4 2 4 4 2 2 2 2 2 2 4 4 4 4 2 4 4 2 2 2 4 2 4
 2 2 2 2 2 2 2 2 4 4 2 2 

In [9]:
print(y_test)

[4 2 2 2 2 2 4 2 2 2 2 2 2 2 2 4 4 4 2 4 2 2 4 2 2 4 2 4 4 4 2 2 4 2 2 2 4
 2 4 2 4 2 4 2 2 2 4 2 2 2 2 2 2 2 2 2 2 4 2 2 4 2 4 2 2 2 2 4 4 2 4 2 2 2
 2 2 4 2 2 4 2 4 2 2 2 2 2 2 2 2 2 4 2 2 2 2 4 4 2 4 2 2 2 2 4 2 4 2 4 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 4 2 4 4 2 4 2 2 2 2 4 2 2]


IMPLEMENT FEATURE SCALING

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [11]:
print(x_train)

[[-0.53357297  0.864401    0.89093807 ...  1.44397328  0.30650783
   2.395609  ]
 [ 0.21693268  0.15997869 -0.72196706 ... -0.19598389 -0.64616737
  -0.36972401]
 [ 0.03324099  0.15997869 -0.07680501 ... -0.19598389 -0.64616737
  -0.36972401]
 ...
 [-0.89491134 -0.54444362 -0.72196706 ... -0.19598389 -0.64616737
  -0.36972401]
 [-0.01171395  0.51218985 -0.07680501 ...  0.2140054  -0.64616737
  -0.36972401]
 [-0.98012792 -1.24886593 -0.72196706 ... -0.60597319 -0.64616737
  -0.36972401]]


LOGISTICS REGRESSION

In [12]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state = 0)
lr.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [13]:
lr_pred = lr.predict(x_test)

K-NEAREST NEIGHBOR

In [14]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [15]:
knn_pred = knn.predict(x_test)

SUPPORT VECTOR CLASSIFICATION

In [16]:
from sklearn.svm import SVC
svc = SVC(kernel = 'linear', random_state = 0)
svc.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [17]:
svc_pred = svc.predict(x_test)

KERNEL SUPPORT VECTOR CLASSIFICATION

In [18]:
from sklearn.svm import SVC
ksvc = SVC(kernel = 'rbf', random_state = 0)
ksvc.fit(x_train, y_train)

SVC(random_state=0)

In [19]:
ksvc_pred = ksvc.predict(x_test)

NAIVE BAYES CLASSIFICATION

In [20]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(x_train, y_train)

GaussianNB()

In [21]:
nb_pred = nb.predict(x_test)

DECISION TREE CLASSIFICATION

In [22]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
dtc.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [23]:
dtc_pred = dtc.predict(x_test)

RANDOM FOREST CLASSIFICATION

In [24]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 40, criterion = 'entropy', random_state = 0)
rfc.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=40, random_state=0)

In [25]:
rfc_pred = rfc.predict(x_test)

CHECK THE ACCURACY SCORE OF EACH CLASSIFICATION

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix
print(
    'Accuracy score for Logistics Regression ', accuracy_score(y_test, lr_pred), '\n', confusion_matrix(y_test, lr_pred), '\n'
    'Accuracy score for K-Nearest Neghbors ', accuracy_score(y_test, knn_pred), '\n', confusion_matrix(y_test, knn_pred), '\n'
    'Accuracy score for Support Vector Classifier ', accuracy_score(y_test, svc_pred), '\n', confusion_matrix(y_test, svc_pred), '\n'
    'Accuracy score for Kernel Support Vector ', accuracy_score(y_test, ksvc_pred), '\n', confusion_matrix(y_test, ksvc_pred), '\n'
    'Accuracy score for Naive Bayes ', accuracy_score(y_test, nb_pred), '\n', confusion_matrix(y_test, nb_pred), '\n'
    'Accuracy score for Decision Tree ', accuracy_score(y_test, dtc_pred), '\n', confusion_matrix(y_test, dtc_pred), '\n'
    'Accuracy score for Random Forest', accuracy_score(y_test, rfc_pred), '\n', confusion_matrix(y_test, rfc_pred), '\n'
)


Accuracy score for Logistics Regression  0.948905109489051 
 [[94  5]
 [ 2 36]] 
Accuracy score for K-Nearest Neghbors  0.948905109489051 
 [[94  5]
 [ 2 36]] 
Accuracy score for Support Vector Classifier  0.948905109489051 
 [[94  5]
 [ 2 36]] 
Accuracy score for Kernel Support Vector  0.948905109489051 
 [[94  5]
 [ 2 36]] 
Accuracy score for Naive Bayes  0.948905109489051 
 [[93  6]
 [ 1 37]] 
Accuracy score for Decision Tree  0.9562043795620438 
 [[95  4]
 [ 2 36]] 
Accuracy score for Random Forest 0.948905109489051 
 [[94  5]
 [ 2 36]] 

